# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3053f2894b7787251cd079df64ec1c94e83c4e991746fcd3a6bd5030eb69aa55311a5b65e180bd2cefefcf18e32c25df9d90a50afe0a36bdc14fdc283b32064
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  
test:
  secret_key_base: ce48d457e9b0636772bee987094e77328a01a68c23ae06e82516223b74770f1b90cd018bec24231ad3a9aab8afe0a8bd4fff289027055ec75dec541f5c459399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
